### ISSUE TITLE
Throwing error when create a sample npm module under windows 7 starter OS

### ISSUE THREAD

**Issue by byteshiva** [domharrington/generator-npm-module#9]
Generator Throwing error when creating a sample npm module under windows 7 starter OS

```javascript

C:\github\sample\12\node_modules\.bin\_mocha:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.Module._extensions..js (C:\github\sample\12\node_modules\istanbul\
lib\hook.js:102:13)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (C:\github\sample\12\node_modules\istanbul\lib\command\common\run-w
ith-cover.js:116:16)
    at C:\github\sample\12\node_modules\istanbul\lib\command\common\run-with-cov
er.js:241:17
    at C:\github\sample\12\node_modules\istanbul\lib\util\file-matcher.js:68:16
npm ERR! Test failed.  See above for more details.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! teet@0.0.0 prepublish: `npm test && npm prune`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the teet@0.0.0 prepublish script 'npm test && npm prune'.
npm ERR! This is most likely a problem with the teet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test && npm prune
npm ERR! You can get their info via:
npm ERR!     npm owner ls teet
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\github\sample\12\npm-debug.log

```

**Comment by domharrington** [comment]
Thanks for the report. From your stack trace it looks as though it is an issue in `istanbul`. I'll investigate further

**Comment by domharrington** [comment]
As a workaround, you could try removing this line from the package.json

`"test": "./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha test",`

**Comment by byteshiva** [comment]
Thee workaround worked, as a workaround I have renamed fieldname from test to __test

```json
    "__test": "istanbul cover ./node_modules/.bin/_mocha test",

```

**Comment by domharrington** [comment]
Does this ever get run? Can it not be removed? I think it is related to this issue: https://github.com/gotwarlost/istanbul/issues/13
